# Generated by Django 4.2.1 on 2023-05-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='trending',
            field=models.BooleanField(default=False, help_text='0=default, 1=Trending'),
        ),
    ]
