# Generated by Django 4.2.1 on 2023-05-16 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_size_product_variant_variants_gallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
